name: build-and-release

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@6934eeffc79f349e3d8719a99823fe6da6a163eb # main
    needs: build
    if: "${{ success() && always() && ! startsWith(github.event.head_commit.message, 'chore(release): ') }}"
    permissions:
      contents: write # for creating release

  upload-release-artifact:
    runs-on: ubuntu-24.04
    needs: release
    if: ${{ success() && always() && needs.release.outputs.tag }}
    permissions:
      contents: write # for uploading release artifact

    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build-result
          path: ./result

      - name: Upload Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: result/lib/CustomModels.dll
          tag_name: ${{ needs.release.outputs.tag }}
