name: build-and-release

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@6a0497c03cf856443b73736cd25c11698e58fc5d # main
    needs: build
    if: "${{ success() && always() && ! startsWith(github.event.head_commit.message, 'chore(release): ') }}"
    permissions:
      contents: write # for creating release

  upload-release-artifact:
    runs-on: ubuntu-24.04
    needs: release
    if: ${{ success() && always() && needs.release.outputs.tag }}
    permissions:
      contents: write # for uploading release artifact

    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build-result
          path: ./result

      - name: Upload Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: result/lib/CustomModels.dll
          tag_name: ${{ needs.release.outputs.tag }}
